service: series-api

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: index.handler
    events:
        - http: ANY /
          cors: true
        - http: 'ANY {proxy+}'
          cors: true

plugins:
  - serverless-offline
