service: series-api

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: index.handler
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
    environment:
      API_URL: ${env:API_URL}

plugins:
  - serverless-offline
